SCREEN_SIZE = WIDTH, HEIGHT = (1200, 900)

# If you want to see all the tiles at once, WORLD_SIZE * TILE_SIZE == SCREEN_SIZE
WORLD_SIZE = (256, 256)
TILE_SIZE = (16, 16)
CHUNK_SIZE = (16, 16)

WORLD_SCALE = 1.0 # WORLD_SCALE in meters

# DEBUG GLOBALS BELOW
DRAW_CHUNK_OUTLINES = False